[build]
builder = "nixpacks"
buildCommand = "npm install --prefix frontend && npm run build --prefix frontend"

[deploy]
startCommand = "npx serve -s frontend/build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
NODE_ENV = "production"
