[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npx serve -s build -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
NODE_ENV = "production"
